name: Build and Push Docker Image

on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get release version (for releases)
        id: get_version
        if: github.event_name == 'release'
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image (for releases)
        if: github.event_name == 'release'
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)

          docker buildx build \
            --platform linux/amd64 \
            --tag narthanaj/html-to-pdf-action:$VERSION \
            --tag narthanaj/html-to-pdf-action:$MAJOR.$MINOR \
            --tag narthanaj/html-to-pdf-action:$MAJOR \
            --push .

      - name: Build and push Docker image (for main branch pushes)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --tag narthanaj/html-to-pdf-action:latest \
            --push .